---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  vars:
    irules: ['irule1', 'irule2']

  tasks:
    - name: ADD iRules
      f5networks.f5_modules.bigip_irule:
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 8443
          validate_certs: false
        module: "ltm"
        name: "{{item}}"
        content: "{{lookup('file','{{item}}')}}"
      with_items: "{{irules}}"
      
    - name: ATTACH iRules TO VIRTUAL SERVER
      f5networks.f5_modules.bigip_virtual_server:
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 8443
          validate_certs: false
        name: "vip"
        irules: "{{irules}}"
