---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  tasks:
    - name: CREATE POOL
      f5networks.f5_modules.bigip_pool:
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 8443
          validate_certs: false
        name: "http_pool"
        lb_method: "round-robin"
        monitors: "/Common/http"
        monitor_type: "and_list"
