---
- name: Disabling a pool member
  hosts: lb
  connection: local
  gather_facts: false
  tasks:
    - name: Setup provider
      set_fact:
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 8443
          validate_certs: false

    - name: Discover pool names
      f5networks.f5_modules.bigip_device_info:
        provider: "{{provider}}"
        gather_subset:
        - ltm-pools
      register: bigip_device_facts

#    - name: "View complete output"
#      debug: "msg={{bigip_device_facts}}"

    - name: "Show members belonging to pool"
      debug: "msg={{item}}"
      loop: "{{bigip_device_facts.ltm_pools | community.general.json_query(query_string)}}"
      vars:
        query_string: "[?name=='http_pool'].members[*].name[]"

    - name: "Disable pool members"
      f5networks.f5_modules.bigip_pool_member:
        provider: "{{provider}}"
        state: "disabled"
# Big hints here: https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigip_pool_member_module.html
        name: "{{hostvars[item].inventory_hostname}}"
        host: "{{hostvars[item].ansible_host}}"
        port: "80"
        pool: "http_pool"
      loop: "{{ groups['web'] }}"
